// Dados de demonstração para quando Supabase não estiver configurado
export const mockCategories = [
  {
    id: '1',
    name: 'Tecnologia',
    description: 'Produtos eletrônicos e gadgets',
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Roupas',
    description: 'Vestuário e acessórios de moda',
    created_at: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Acessórios',
    description: 'Acessórios diversos e utilidades',
    created_at: new Date().toISOString(),
  },
];

export const mockProducts = [
  {
    id: '1',
    name: 'Smartphone Premium',
    description: 'Smartphone de última geração com câmera de alta resolução e processador avançado.',
    price: 1299.90,
    stock_quantity: 50,
    category_id: '1',
    image_url: 'https://images.pexels.com/photos/607812/pexels-photo-607812.jpeg?auto=compress&cs=tinysrgb&w=800',
    created_at: new Date().toISOString(),
    category: mockCategories[0],
  },
  {
    id: '2',
    name: 'Notebook Gamer',
    description: 'Notebook para jogos com placa de vídeo dedicada e alta performance.',
    price: 2899.90,
    stock_quantity: 25,
    category_id: '1',
    image_url: 'https://images.pexels.com/photos/205421/pexels-photo-205421.jpeg?auto=compress&cs=tinysrgb&w=800',
    created_at: new Date().toISOString(),
    category: mockCategories[0],
  },
  {
    id: '3',
    name: 'Camiseta Premium',
    description: 'Camiseta de algodão premium com design exclusivo e alta qualidade.',
    price: 89.90,
    stock_quantity: 100,
    category_id: '2',
    image_url: 'https://images.pexels.com/photos/996329/pexels-photo-996329.jpeg?auto=compress&cs=tinysrgb&w=800',
    created_at: new Date().toISOString(),
    category: mockCategories[1],
  },
  {
    id: '4',
    name: 'Tênis Esportivo',
    description: 'Tênis confortável para corrida e atividades físicas com tecnologia de amortecimento.',
    price: 299.90,
    stock_quantity: 75,
    category_id: '2',
    image_url: 'https://images.pexels.com/photos/2529148/pexels-photo-2529148.jpeg?auto=compress&cs=tinysrgb&w=800',
    created_at: new Date().toISOString(),
    category: mockCategories[1],
  },
  {
    id: '5',
    name: 'Relógio Inteligente',
    description: 'Smartwatch com monitoramento de saúde e conectividade avançada.',
    price: 599.90,
    stock_quantity: 40,
    category_id: '3',
    image_url: 'https://images.pexels.com/photos/437037/pexels-photo-437037.jpeg?auto=compress&cs=tinysrgb&w=800',
    created_at: new Date().toISOString(),
    category: mockCategories[2],
  },
  {
    id: '6',
    name: 'Fones Bluetooth',
    description: 'Fones de ouvido sem fio com cancelamento de ruído e alta qualidade de som.',
    price: 199.90,
    stock_quantity: 60,
    category_id: '3',
    image_url: 'https://images.pexels.com/photos/3394650/pexels-photo-3394650.jpeg?auto=compress&cs=tinysrgb&w=800',
    created_at: new Date().toISOString(),
    category: mockCategories[2],
  },
  {
    id: '7',
    name: 'Tablet Pro',
    description: 'Tablet profissional com tela de alta resolução e processador potente.',
    price: 899.90,
    stock_quantity: 30,
    category_id: '1',
    image_url: 'https://images.pexels.com/photos/1334597/pexels-photo-1334597.jpeg?auto=compress&cs=tinysrgb&w=800',
    created_at: new Date().toISOString(),
    category: mockCategories[0],
  },
  {
    id: '8',
    name: 'Jaqueta Moderna',
    description: 'Jaqueta estilosa e confortável para todas as ocasiões.',
    price: 159.90,
    stock_quantity: 45,
    category_id: '2',
    image_url: 'https://images.pexels.com/photos/1040945/pexels-photo-1040945.jpeg?auto=compress&cs=tinysrgb&w=800',
    created_at: new Date().toISOString(),
    category: mockCategories[1],
  },
];

export const mockReviews = [
  {
    id: '1',
    product_id: '1',
    customer_name: 'João Silva',
    rating: 5,
    comment: 'Excelente produto! Superou minhas expectativas, bateria dura o dia todo.',
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    product_id: '1',
    customer_name: 'Maria Santos',
    rating: 4,
    comment: 'Muito bom, câmera incrível. Apenas o preço um pouco alto.',
    created_at: new Date().toISOString(),
  },
  {
    id: '3',
    product_id: '2',
    customer_name: 'Carlos Oliveira',
    rating: 5,
    comment: 'Perfeito para jogos! Roda tudo no máximo sem travamentos.',
    created_at: new Date().toISOString(),
  },
  {
    id: '4',
    product_id: '3',
    customer_name: 'Ana Costa',
    rating: 4,
    comment: 'Tecido de ótima qualidade, muito confortável.',
    created_at: new Date().toISOString(),
  },
  {
    id: '5',
    product_id: '4',
    customer_name: 'Pedro Almeida',
    rating: 5,
    comment: 'Tênis muito confortável, ideal para corrida.',
    created_at: new Date().toISOString(),
  },
  {
    id: '6',
    product_id: '5',
    customer_name: 'Lucia Ferreira',
    rating: 4,
    comment: 'Smartwatch com muitas funcionalidades úteis.',
    created_at: new Date().toISOString(),
  },
];